version: '3.1'
services:
  postgres-db:
    image: postgres
    restart: always
    container_name: postgres # 컨테이너 이름 설정
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"      
    volumes:
      - ${POSTGRES_HOME_DIR}/data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default
#    privileged: true

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 80:80
    networks:
      - default
    environment:
      - TZ=Asia/Seoul
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
#    privileged: true

networks:
  default:
    external:
      name: databases